{
 "title": "Formicarium",
 "time": { "from": "2022-08-27T00:00:00.000Z", "to": "2022-08-30T23:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "NodeV",
    "label": "Plant",
    "query": "SELECT\n  Node AS __value, Name AS __text\nFROM Lookup v;"
   }
  ]
 },
 "panels": [
  { "title": "$NodeV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "NodeV" },
  {
   "title": "Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Time AS \"time\",\n  Temperature\nFROM anthill\nWHERE\n  $__timeFilter(Time)\n  AND substring(Node,1) IN ($NodeV)\nORDER BY Time"
    }
   ]
  },
  {
   "title": "Soil Moisture",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Time AS \"time\",\n  Moisture\nFROM anthill\nWHERE\n  $__timeFilter(Time)\n  AND substring(Node,1) IN ($NodeV)\nORDER BY Time"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Time AS \"time\",\n  Humidity\nFROM anthill\nWHERE\n  $__timeFilter(Time)\n  AND substring(Node,1) IN ($NodeV)\nORDER BY Time"
    }
   ]
  },
  {
   "title": "$NodeV",
   "type": "annolist",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  Time AS \"time\",\n  Light\nFROM anthill\nWHERE\n  $__timeFilter(Time)\nORDER BY Time"
    }
   ]
  },
  {
   "title": "Average Light",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Time AS \"time\",\n  light\nFROM anthill\nWHERE\n  $__timeFilter(Time)\n  AND substring(Node,1) IN ($NodeV)\nORDER BY Time"
    }
   ]
  },
  {
   "title": "Current Light",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Time AS \"time\",\n  light\nFROM anthill\nWHERE\n  $__timeFilter(Time)\n  AND substring(Node,1) IN ($NodeV)\nORDER BY Time"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Time,$__interval),\n  avg(Temperature) AS \"Temperature\",\n  Node as \"Node\"\nFROM anthill\nWHERE\n  $__timeFilter(Time)\n  AND substring(Node,1) IN ($NodeV) \nGROUP BY 1\nORDER BY $__timeGroup(Time,$__interval)"
    }
   ]
  },
  {
   "title": "Light, Humidity & Mosture",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Time,$__interval),\n  avg(Moisture) AS \"Moisture\",\n  avg(Humidity) AS \"Humidity\",\n  avg(Light) AS \"Light\",\n  \n  Node AS \"Node\"\nFROM anthill\nWHERE\n  $__timeFilter(Time)\n  AND substring(Node,1) IN ($NodeV) \nGROUP BY 1 \nORDER BY $__timeGroup(Time,$__interval)"
    }
   ]
  }
 ]
}